services:
  fastapi:
    build:
      context: ./src/backend/api
      dockerfile: Dockerfile
    container_name: fastapi
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - venv:/app/.venv
    environment:
      - VITE_API_URL=http://fastapi:8000
      - PYTHONUNBUFFERED=1
    command: sh -c "pip install uvicorn && python -m src.backend.api.main"
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      neo4j:
        condition: service_healthy
      ollama:
        condition: service_started

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"  # Ollama HTTP API
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    networks:
      - app-network
    environment:
      - OLLAMA_MODELS=/root/.ollama/models
    mem_limit: 10G
    cpus: 2

  neo4j:
    image: neo4j:5.13.0
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/import
      - neo4j_plugins:/plugins
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:7474" ]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 120s
    environment:
       - NEO4J_AUTH=${NEO4J_USERNAME}/${NEO4J_PASSWORD}
       - NEO4J_server_memory_heap_max__size=2G
       - NEO4J_server_memory_pagecache_size=1G
       - NEO4J_server_jvm_additional=-XX:+ExitOnOutOfMemoryError -XX:+HeapDumpOnOutOfMemoryError
       - NEO4J_db_transaction_timeout=30m
       - NEO4J_db_checkpoint_interval_time=5m
       - NEO4J_apoc_export_file_enabled=true
       - NEO4J_apoc_import_file_enabled=true
       - NEO4J_apoc_import_file_use__neo4j__config=true
       - NEO4J_dbms_security_procedures_unrestricted=apoc.*,algo.*
       - NEO4J_server_bolt_listen__address=0.0.0.0:7687
       - NEO4J_PLUGINS=["apoc"]
    networks:
      - app-network
    restart: unless-stopped
    mem_limit: 4G
    cpus: 2

  frontend:
    build:
      context: ./src/vulnerability-frontend
    container_name: frontend
    environment:
      - VITE_API_URL=http://localhost:8000
      - ROLLUP_DISABLE_NATIVE=1
    ports:
      - "5173:5173"
    volumes:
      - ./src/vulnerability-frontend:/app
      - node_modules:/app/node_modules
    networks:
      - app-network
    depends_on:
      - fastapi

volumes:
  node_modules:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:
  ollama_data:
  venv:

networks:
  app-network:
    driver: bridge
